import '@nomiclabs/hardhat-ethers';
import { runAsyncMain } from '../../../helpers';
import { getDeployContext } from '../../deploy-context';
import { DEFAULT_SETTINGS } from '../../default-settings';
import { createBexAutoCompounder, createKodiakAutoCompounder } from '../../factory-creators';

async function main() {
    const { owner, ADDRS, INSTANCES } = await getDeployContext(__dirname);

    // OHM/HONEY
    await createKodiakAutoCompounder(
      'VAULTS.INFRARED_AUTO_COMPOUNDER_OHM_HONEY_A',
      owner,
      ADDRS,
      INSTANCES.FACTORIES.INFRARED_AUTO_COMPOUNDER.FACTORY,
      DEFAULT_SETTINGS.VAULTS.INFRARED_AUTO_COMPOUNDERS.OHM_HONEY,
      ADDRS.EXTERNAL.INFRARED.REWARD_VAULTS.OHM_HONEY,
      ADDRS.VAULTS.INFRARED_AUTO_COMPOUNDER_OHM_HONEY_A.OVERLORD_WALLET
    );

    // BYUSD/HONEY
    await createBexAutoCompounder(
      'VAULTS.INFRARED_AUTO_COMPOUNDER_BYUSD_HONEY_A',
      owner,
      ADDRS,
      INSTANCES.FACTORIES.INFRARED_AUTO_COMPOUNDER.FACTORY,
      DEFAULT_SETTINGS.VAULTS.INFRARED_AUTO_COMPOUNDERS.BYUSD_HONEY,
      ADDRS.EXTERNAL.INFRARED.REWARD_VAULTS.BYUSD_HONEY,
      ADDRS.VAULTS.INFRARED_AUTO_COMPOUNDER_BYUSD_HONEY_A.OVERLORD_WALLET
    );

    // rUSD/HONEY
    await createKodiakAutoCompounder(
      'VAULTS.INFRARED_AUTO_COMPOUNDER_RUSD_HONEY_A',
      owner,
      ADDRS,
      INSTANCES.FACTORIES.INFRARED_AUTO_COMPOUNDER.FACTORY,
      DEFAULT_SETTINGS.VAULTS.INFRARED_AUTO_COMPOUNDERS.RUSD_HONEY,
      ADDRS.EXTERNAL.INFRARED.REWARD_VAULTS.RUSD_HONEY,
      ADDRS.VAULTS.INFRARED_AUTO_COMPOUNDER_RUSD_HONEY_A.OVERLORD_WALLET
    );

    // WBERA/iBERA
    await createKodiakAutoCompounder(
      'VAULTS.INFRARED_AUTO_COMPOUNDER_WBERA_IBERA_A',
      owner,
      ADDRS,
      INSTANCES.FACTORIES.INFRARED_AUTO_COMPOUNDER.FACTORY,
      DEFAULT_SETTINGS.VAULTS.INFRARED_AUTO_COMPOUNDERS.WBERA_IBERA,
      ADDRS.EXTERNAL.INFRARED.REWARD_VAULTS.WBERA_IBERA,
      ADDRS.VAULTS.INFRARED_AUTO_COMPOUNDER_WBERA_IBERA_A.OVERLORD_WALLET
    );

    // WBERA/HONEY
    await createKodiakAutoCompounder(
      'VAULTS.INFRARED_AUTO_COMPOUNDER_WBERA_HONEY_A',
      owner,
      ADDRS,
      INSTANCES.FACTORIES.INFRARED_AUTO_COMPOUNDER.FACTORY,
      DEFAULT_SETTINGS.VAULTS.INFRARED_AUTO_COMPOUNDERS.WBERA_HONEY,
      ADDRS.EXTERNAL.INFRARED.REWARD_VAULTS.WBERA_HONEY,
      ADDRS.VAULTS.INFRARED_AUTO_COMPOUNDER_WBERA_HONEY_A.OVERLORD_WALLET
    );

    // WBERA/IBGT
    await createKodiakAutoCompounder(
      'VAULTS.INFRARED_AUTO_COMPOUNDER_WBERA_IBGT_A',
      owner,
      ADDRS,
      INSTANCES.FACTORIES.INFRARED_AUTO_COMPOUNDER.FACTORY,
      DEFAULT_SETTINGS.VAULTS.INFRARED_AUTO_COMPOUNDERS.WBERA_IBGT,
      ADDRS.EXTERNAL.INFRARED.REWARD_VAULTS.WBERA_IBGT,
      ADDRS.VAULTS.INFRARED_AUTO_COMPOUNDER_WBERA_IBGT_A.OVERLORD_WALLET
    );
}

runAsyncMain(main);
